security:
  oauth2:
    client:
      clientId: oauth2-app-client
      userAuthorizationUri: https://Mazeed-WIN-U1MOKU0DM3T-CA/adfs/oauth2/authorize?resource=http://localhost:8080/web-app
      accessTokenUri: https://Mazeed-WIN-U1MOKU0DM3T-CA/adfs/oauth2/token
      tokenName: code
      authenticationScheme: query
      clientAuthenticationScheme: form
      grant-type: authorization_code
    resource:
      userInfoUri: https://Mazeed-WIN-U1MOKU0DM3T-CA/adfs/oauth2/token

logging:
  level:
    com.example.demo: TRACE
    org.springframework.security: TRACE

server:
  port: 8080
  
#client:
#    ssl:
#        truststore: file:classpath:adfs_access_token_certificate.cer
        #trustStorePassword: 123456